const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Behaviors.wrap,
		C3.Behaviors.Flash,
		C3.Behaviors.LOS,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.random
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Physics: 0},
	{Tilemap: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Anchor: 0},
	{LeftButton: 0},
	{RightButton: 0},
	{JumpButton: 0},
	{Jumpthru: 0},
	{Floating: 0},
	{Sine: 0},
	{Moving: 0},
	{Water: 0},
	{Border: 0},
	{Touch: 0},
	{Thorns: 0},
	{FlameWheel: 0},
	{Rotate: 0},
	{Sawtooth: 0},
	{Bullet: 0},
	{Fade: 0},
	{PlayerDie: 0},
	{PlayerParticles: 0},
	{Coin: 0},
	{Diamond: 0},
	{Score: 0},
	{Life: 0},
	{Start: 0},
	{Keyboard: 0},
	{CoinParticles: 0},
	{DiamondParticles: 0},
	{Mouse: 0},
	{Replay: 0},
	{GameOver: 0},
	{Platformer: 0},
	{Barrier: 0},
	{Key: 0},
	{Door: 0},
	{KeyCounter: 0},
	{Button: 0},
	{Laserbeam: 0},
	{Beamshooter: 0},
	{Pin: 0},
	{Gun: 0},
	{Laser: 0},
	{ShootButton: 0},
	{ChainBlade: 0},
	{KeyIcon: 0},
	{Dropweight: 0},
	{Audio: 0},
	{Wrap: 0},
	{Flash: 0},
	{Fly: 0},
	{EnemyParticles: 0},
	{HelllWorm: 0},
	{Frog: 0},
	{EnemySensor: 0},
	{Spider: 0},
	{KeyRequired: 0},
	{Lock: 0},
	{LockParticles: 0},
	{LineOfSight: 0},
	{Enemy: 0},
	{EnemyBullets: 0},
	{WeakStone: 0},
	{Durability: 0},
	{Crate: 0},
	{CrateParticles: 0},
	{Creator: 0},
	{Obstacles: 0},
	{Bullets: 0},
	{Level: 0},
	{HoldingGun: 0},
	{Duration: 0},
	{pistol: 0},
	{StartGame: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	LeftButton: class extends self.ISpriteInstance {},
	RightButton: class extends self.ISpriteInstance {},
	JumpButton: class extends self.ISpriteInstance {},
	Floating: class extends self.ISpriteInstance {},
	Moving: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Thorns: class extends self.ISpriteInstance {},
	FlameWheel: class extends self.ISpriteInstance {},
	Sawtooth: class extends self.ISpriteInstance {},
	PlayerDie: class extends self.ISpriteInstance {},
	PlayerParticles: class extends self.IParticlesInstance {},
	Coin: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteFontInstance {},
	Life: class extends self.ISpriteFontInstance {},
	Start: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	CoinParticles: class extends self.IParticlesInstance {},
	DiamondParticles: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	Replay: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteFontInstance {},
	Platformer: class extends self.ISpriteFontInstance {},
	Barrier: class extends self.ISpriteInstance {},
	Key: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	KeyCounter: class extends self.ISpriteFontInstance {},
	Button: class extends self.ISpriteInstance {},
	Laserbeam: class extends self.ISpriteInstance {},
	Beamshooter: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	Laser: class extends self.ISpriteInstance {},
	ShootButton: class extends self.ISpriteInstance {},
	ChainBlade: class extends self.ISpriteInstance {},
	KeyIcon: class extends self.ISpriteInstance {},
	Dropweight: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Fly: class extends self.ISpriteInstance {},
	EnemyParticles: class extends self.IParticlesInstance {},
	HelllWorm: class extends self.ISpriteInstance {},
	Frog: class extends self.ISpriteInstance {},
	EnemySensor: class extends self.ISpriteInstance {},
	Spider: class extends self.ISpriteInstance {},
	Lock: class extends self.ISpriteInstance {},
	LockParticles: class extends self.IParticlesInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyBullets: class extends self.ISpriteInstance {},
	WeakStone: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	CrateParticles: class extends self.IParticlesInstance {},
	Creator: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	Bullets: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {}
}